### ISSUE TITLE
Getting non-jpeg header bytes with examples\1_basic-output-size

### ISSUE THREAD

**Issue by SelfTide** [zhaochenyuangit/ArduCAM-ESP32#1]
Equipment used:

ESPWROOM32 Devkit V1
ArduCAM OV2640-MINI-2MP-PLUS

I followed the build process using ESP-IDF command line from the project directory:

`>idf.py build flash monitor`

But after flash and connection, this is what I get:
```
SPI: interface OK
I2C: OV2640 detected.
initialize camera, may take up to one minute
frame 1 captured image! size: 3592, first four bytes are: ff fc ff f0
```
The only thing I have changed is GPIO pins, I switched out GPIO 26 for GPIO 19 in `interface_spi.h` would this possibly be a problem with frequency? I did check the FAQ you had left a nice link to and it did mention something about that. https://www.arducam.com/docs/spi-cameras-for-arduino/faq/#q3-due-to-the-large-number-of-user-controller-platforms-the-poor
would this have anything to do with this?

**Comment by SelfTide** [comment]
Okay, seems like I figured out the issue. 
It did turn out to be a frequency issue. 

In `interface_spi.h` under `spi_master_init(void)` frequency was set as such:
`.clock_speed_hz = SPI_MASTER_FREQ_8M / 8 * 7, //must be strictly slow than ArduChip SPI 8MHz`

I checked against what was in the build for arduino and this is what I found in `SPI.cpp` under `SPIClass(uint8_t spi_bus)`:
`,_freq(1000000)` <--- this just seems like they are doing a frequency to clock division setup.

Where as `spi_device_interface_config_t` will happily just take a frequency given in int format per <a href="https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html#_CPPv4N29spi_device_interface_config_t14clock_speed_hzE">SPI Master Driver API</a>

I set `clock_speed_hz` manually to 6.5MHz like so:
`.clock_speed_hz = 6500000,`

This seems to be as high as it will go for me with out an issue.

I have not confirmed this to be completely working just yet and I haven't had time to get it to work with what I'm working on to check for a solid image just yet. when and if I do I will close this issue.

**Comment by zhaochenyuangit** [comment]
Yes do check the SPI frequency, because the camera device produces a new image binary at a constant frequency, if your MCU consumes faster than it errors will occur.

**Comment by SelfTide** [comment]
Yup, that seems to have fixed the issue. Got a good 320x240 image with that frequency. closing this.
