### ISSUE TITLE
Question, C wrapper functions.

### ISSUE THREAD

**Issue by SelfTide** [zhaochenyuangit/ArduCAM-ESP32#2]
I have made edits to `ArduCAM_esp_ov2640.cpp` and `ArduCAM_esp_ov2640.h` to include C wrapper functions for this component. Would it be okay to add those? this project worked for me in C and I would like to include those to possibly help others that might find this library.

**Comment by zhaochenyuangit** [comment]
Sure the patch looks good to me. Thanks for the contribution
