### ISSUE TITLE
Conflicting declaration myCAM

### ISSUE THREAD

**Issue by hendrikvg** [zhaochenyuangit/ArduCAM-ESP32#5]
While building example 1_BASIC-OUTPUT-SIZE I get the following error.

error: conflicting declaration 'ArduCAM_OV2640 myCAM'
   21 | ArduCAM_OV2640 myCAM(CS_PIN);
note: previous declaration as 'ArduCAM_OV2640_C* myCAM'
   32 |         ArduCAM_OV2640_C *myCAM;

What might cause this, and what would the solution be?

**Comment by SelfTide** [comment]
Sorry about that, that is an issue with the C compatibility code. Right now you can comment out `ArduCAM_OV2640_C *myCAM;` in `ArduCAM_esp_ov2640.h` line 32 and that should fix this issue.

**Comment by hendrikvg** [comment]
Thank you for your quick response! I require the C compatibility, commenting it out causes different errors, as then myCAM hasn't been defined in the scope of `ArduCAM_esp_ov2540.cpp`.

**Comment by SelfTide** [comment]
That's my fault, I didn't think the naming out so much past the scope of the project I was working on and didn't think to compile and test the examples that were in the library it's self. my apologies, but I do have a solution for you.
So, I have made the changes here https://github.com/SelfTide/ArduCAM-ESP32 till I can have the branch merged with this one. let me know if you have any issues with the fork, if you do just let me know and I'll fix it as soon as I am able.

**Comment by hendrikvg** [comment]
Hi, it keeps saying:
"ArduCAM-ESP32-master/components/arducam_esp/ArduCAM_esp_ov2640.h:32: multiple definition of `myCAM_C'; esp-idf/main/libmain.a(main.cpp.obj):ArduCAM-ESP32-master_C-compatible/ArduCAM-ESP32-master/components/arducam_esp/ArduCAM_esp_ov2640.h:32: first defined here"

Maybe I minsunderstood some instructions? 
I am using ESP-IDF v1.5.1 to compile the first example for an esp32s3 (the DevKitC-1 board from Espressif). I added `REQUIRES driver` to the `CMakeLists.txt` in components to have it find `driver/gpio.h`. Additionally I had to change `portTICK_RATE_MS` to `portTICK_PERIOD_MS` on lines 47 and 60 in `interface_i2c.c`. I also changed the gpio pins to suit my board, but I haven't gotten it to compile yet due to aforementioned problems.

**Comment by SelfTide** [comment]
No, you didn't misunderstand anything. Just an issue with the examples and a variable being in a header file... I pulled myCAM_C out of the header file and placed it in the .cpp file where it should probably have been in the first place. The code has been updated in regards to this on github @ https://github.com/SelfTide/ArduCAM-ESP32 that should fix it, so you probably just need to download `ArduCAM_esp_ov2640.h` and `ArduCAM_esp_ov2640.cpp` respectively. all examples compile on my end.
As for the `driver/gpio.h` I did see somebody else have an issue with this with ESP-IDF v1.5.1 in regards to this. Along with the portTICK_* that must also be a change with v1.5.1 thanks for the heads up about that. I'll probably be updating my ESP-IDF soon so I'll be looking in to that.

**Comment by hendrikvg** [comment]
Thank you, it seems to work! Because I'm using the ESP-S3 I still had to change line 17 in `interface_spi.c` to `err = spi_bus_initialize(SPI_PORT, &buscfg, SPI_DMA_CH_AUTO);`.
Thanks again! :)

**Comment by zhaochenyuangit** [comment]
Hey I am happy to see your problem solved, it has been a long time that I use an Espressif dev board. I did not verified the function of the code by merging. The hanging PR is the fix to this issue right, @hendrikvg ?

**Comment by hendrikvg** [comment]
Sorry, but I don't know what you mean with "hanging PR".
